### Jaime Alvarez -- August 2016

=begin
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
=end

# This Hash function returns the Fibonacci term for the specified index in the sequence
fibonacci = Hash.new{ |h,k| h[k] = k < 2 ? k : h[k-1] + h[k-2] }

fib_sum = 0
i = 0
while fibonacci[i] < 4000000
  f = fibonacci[i]
  fib_sum += f if f % 2 == 0
  
  i += 1
end

puts "Fibonacci Even Sum = %d" % fib_sum