### Jaime Alvarez - March 2016

"""
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?

"""
import math

def factors(number):
    limit = math.ceil(math.sqrt(number))
    f = []
    for i in range(1, int(limit)):
        if number % i == 0:
            f.append(i)
            if i != number/i:
                f.append(number/i)
            
    return f

if __name__ == '__main__':
    i = 1
    triangular_number = 0 
    d = 500
    
    while True:
        triangular_number = triangular_number + i
        
        # Check number of divisors
        num_divisors = len(factors(triangular_number))
        
        if num_divisors > d:
            break
        
        i += 1
        
    print "Triangular number with over %s divisors: %s" % (d, triangular_number)