### Jaime Alvarez -- September 2016

=begin
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
=end

def divisors(n)
  1.upto(Math.sqrt(n)).select { |i| (n % i).zero? }.inject([]) do |f, i| 
    f << (n / i) unless i == (n / i)
    f << i
  end.sort
end

def triangle_numbers
  Enumerator.new do |y|
    a = 0
    i = 1
    loop do
      a += i
      y << a
      i += 1
    end
  end
end

triangular_number = 0
triangle_numbers.each do |i| 
  if divisors(i).size > 500
    triangular_number = i
    puts "Answer: #{triangular_number}"
    break
  end
end

