## Jaime Alvarez -- October 2016

=begin
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
Triangle 	  	Tn=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
Pentagonal 	  	Pn=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
Hexagonal 	  	Hn=n(2n−1) 	  	1, 6, 15, 28, 45, ...

It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
=end

def triangle
  Enumerator.new do |y|
    a = 0
    i = 1
    loop do
      a = i * (i + 1) / 2
      y << a
      i += 1
    end
  end
end

def pentagonal
  Enumerator.new do |y|
    a = 0
    i = 1
    loop do
      a = i * (3 * i - 1) / 2
      y << a
      i += 1
    end
  end
end

def hexagonal
  Enumerator.new do |y|
    a = 0
    i = 1
    loop do
      a = i * (2 * i - 1)
      y << a
      i += 1
    end
  end
end

TOP = 100000
answer = 0

triangles = triangle.take(TOP).select { |num| num > 40755 }
pentagonals = pentagonal.take(TOP)
hexagonals = hexagonal.take(TOP)

triangles.each do |num|
  if pentagonals.include?(num) && hexagonals.include?(num)
    answer = num
    break
  end
end

puts "Answer: #{answer}"