### Jaime Alvarez - March 2016

"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

def even_fibonacci(num):
    a = 0
    b = 1
    c = 0
    
    even_sum = 0
    
    for i in range(0, num):
        c = a + b
        a = b
        b = c
        
        # Check if it is even value, and that does not exceed 4,000,000
        if (c % 2 == 0) and ( c < 4000000 ):
            print c
            even_sum += c
            
    return even_sum
        
    
if __name__ == '__main__':
    even_sum = even_fibonacci(60)
    print "Even Sum = ", even_sum